apiVersion: v1
appVersion: "v0.1.0"
description: A Helm chart for Kubernetes
name: kube-iptables-tailer
version: 0.1.5
home: https://github.com/wix-playground/kube-iptables-tailer
keywords:
- kube-iptables-tailer
- iptables
- calico
- networkpolicy
maintainers:
- email: alexshe@wix.com
  name: alexshe
sources:
- https://github.com/wix-playground/kube-iptables-tailer
- https://github.com/box/kube-iptables-tailer